### ISSUE TITLE
Add od4d-footer.png footer image to images/supporters/

### ISSUE THREAD

**Issue by ericdill** [openeemeter/openeemeter.org#1]
There is an image in the footer of openeemeter.org that is not rendering. Looks like the link was added in when [_config.yaml was updated a few days ago](https://github.com/openeemeter/openeemeter.org/commit/5262837761e2beb4e61a738ca63c8155b0e78d6c#diff-aeb42283af8ef8e9da40ededd3ae2ab2R46) but the image wasn't added.  The image referenced is `/img/supporters/od4d-footer.png`.  Additionally the alt-text is "Pacific Gas and Electric" but it seems to be referencing the Open data for development site. 

screenshot on my laptop:

![feb 04-20 44 17](https://cloud.githubusercontent.com/assets/6223243/22623022/c3074c00-eb1a-11e6-9b80-c73360856fe0.png)

**Comment by mcgeeyoung** [comment]
Thanks @ericdill We're adopting the philosophy of release first, fix mistakes later! Appreciate the keen eye here.

**Comment by ericdill** [comment]
Makes sense. You'll never find all the mistakes pre-release anyway :smile:

**Comment by ericdill** [comment]
Fixed by 301bcd635bb8d0756c0d50f7d83db2b6612bd84c
